# -*- coding: utf-8 -*-

# Make seqnames of input stockhomle file unique by variating the last character.
# The aligned sequences are meaningful, only the names duplicate coz limitation
# on the length of name string.
# This script only works with sto generated by reformat.pl (no GS line, no mutiple RF)
#
# Klark (chenke@szbl.ac.cn)
# Last modified 2022/04/03

import sys

seqs = {}
chr_rg = list(range(ord('0'), ord('9')+1))+ \
         list(range(ord('A'), ord('Z')+1))+ \
         list(range(ord('a'), ord('z')+1))
chr_list = [chr(_) for _ in chr_rg]
with open(sys.argv[1], 'r') as f:
    l1 = f.readline()
    while l1:
        if l1[0] == '#':
            print(l1, end='')
        else:
            ll1 = l1.split()
            if len(ll1) < 2:
                print(l1, end='')
            elif len(ll1) == 2:
                if ll1[0] in seqs.keys():
                    if ll1[1] != seqs[ll1[0]]:
                        for last_chr in chr_list:
                            tmpname = ll1[0][:-1] + last_chr
                            if tmpname not in seqs.keys():
                                ll1[0] = tmpname
                                seqs[ll1[0]] = ll1[1]
                                print(f'{ll1[0]:<32s} {ll1[1]}')
                                break
                            elif ll1[1] == seqs[tmpname]:
                                break
                else:
                    seqs[ll1[0]] = ll1[1]
                    print(l1, end='')
            else:
                raise ValueError('Malformated sto')
        l1 = f.readline()


